Style/IdenticalConditionalBranches:
  Exclude:
    - 'test/integration/default/serverspec/localhost/cron_spec.rb'

Style/RegexpLiteral:
  Exclude:
    - 'test/integration/default/serverspec/localhost/cron_spec.rb'
